name = "cloudflare-docker-proxy"
main = "src/index.js"
compatibility_date = "2023-12-01"

[vars]
CUSTOM_DOMAIN = "pvecloud.space"
MODE = "production"
TARGET_UPSTREAM = ""

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "pvecloud.space"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
   { pattern = "docker.pvecloud.space", custom_domain = true },
   { pattern = "quay.pvecloud.space", custom_domain = true },
   { pattern = "gcr.pvecloud.space", custom_domain = true },
   { pattern = "k8s-gcr.pvecloud.space", custom_domain = true },
   { pattern = "k8s.pvecloud.space", custom_domain = true },
   { pattern = "ghcr.pvecloud.space", custom_domain = true },
   { pattern = "cloudsmith.pvecloud.space", custom_domain = true },
   { pattern = "ecr.pvecloud.space", custom_domain = true }
 ]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""
CUSTOM_DOMAIN = "pvecloud.space"

[env.staging]
name = "cloudflare-docker-proxy-staging"
route = { pattern = "docker-staging.pvecloud.space", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
CUSTOM_DOMAIN = "pvecloud.space"


[observability.logs]
enabled = true